version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
  drush:
    image: drush/drush:8
    links:
      - db
    # volumes_from:
    #   - drupal
    volumes:
      - ./app:/app
      - ./db-data:/var/lib/mysql
