version: "2.1"
services:
  db:
    image: mysql:5.7
    container_name: app.db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  drupal:
    container_name: app.drupal
    depends_on:
      db:
        condition: service_healthy
    build: .
    links:
      - db
    ports:
      - "${DRUPAL_PORT}:80"
    volumes:
      - ./app:/app
    restart: always
  # Drush container not working for drupal8, revert to bootstrap.sh script for drush si
  # drush:
  #   container_name: app.drush
  #   image: drush/drush:8
  #   links:
  #     - db
  #   volumes_from:
  #     - drupal
  #   # volumes:
  #   #   - ./app:/app
  #   #   - ./db-data:/var/lib/mysql
